= Trivy scan and publish to Platform

Use this action to perform static application security testing (SAST) on a repository with the Trivy scanner, and then view comprehensive security results in the CloudBees platform.

== Prerequisites

Set up the CloudBees platform and GHA to work together, providing key features of the platform to GHA workflows. Refer to link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/github-actions/gha-getting-started[Getting started with GHA integration] for more information.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `binary-tar-path`
| String
| Yes
| The path of the binary to be scanned.

NOTE: The binary file must be in the TAR format.

| `cloudbees-pat`
| String
| Yes
| The https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/personal-access-token[CloudBees platform personal access token].

| `cloudbees-url`
| String
| No
| The CloudBees platform URL.
The default value is `"https://api.cloudbees.io"`.

| `license`
| Boolean
| No
| The option to perform license scanning.
Specify `license: true` to perform license scanning.

|===

== Usage examples

=== Basic example

The following is a basic example of using this action:

[source,yaml]
----

      - name: Trivy SAST scan
        uses: cloudbees-io-gha/trivy-scan-publish@v1
        with:
          binary-tar-path: example-tar-path.tar
          cloudbees-pat : ${{ secrets.CloudBees-platform-PAT }}
----

=== Example using license scan

In the following example, the license option is enabled to scan the binary for license files, and then output the risk to CloudBees analytics dashboards.
To learn more, refer to the link:https://trivy.dev/v0.33/docs/licenses/scanning/[Trivy license scanning documentation].

[source,yaml]
----

      - name: Trivy SAST scan
        uses: cloudbees-io-gha/trivy-scan-publish@v1
        with:
          binary-tar-path: example-tar-path.tar
          cloudbees-pat: ${{ secrets.CloudBees-platform-PAT }}
          license: true
----

=== Full workflow and run example

The following GHA workflow example builds a Docker binary using link:https://docs.docker.com/reference/cli/docker/buildx/[Buildx], saves the image as a TAR file, and then scans the image with Trivy.


.Example GHA workflow YAML file
[.collapsible]
--

[source, yaml,role="default-expanded"]
----
name: GHA workflow with Trivy SAST scan

on:
  push:
    branches:
      - mains

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Run Trivy SAST scan
        uses: cloudbees-io-gha/trivy-scan-publish@v1
        with:
          binary-tar-path: output.tar
          cloudbees-pat: ${{ secrets.CLOUDBEES_PAT }}

----
--

After the GHA run has completed, the security findings are collected and displayed in the CloudBees platform https://docs.cloudbees.com/docs/cloudbees-platform/latest/aspm/security-center[Security center] of the component containing the workflow.

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/github-actions/intro[Using GitHub Actions with the CloudBees platform].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].

